import { StateSchema } from "@langchain/langgraph";
import { z } from "zod/v4";
import { QuizSchema } from "./agent.schemas";

const QuizState = new StateSchema({
  readme_url: z.string().describe("The URL of the README file for the quiz"),
  source: z
    .string()
    .default("")
    .describe("The Markdown that fetchSource retrieved from readme_url"),
  quiz: QuizSchema.optional().describe(
    "The quiz generated by generateQuestions from the source Markdown",
  ),
  quizId: z.uuid().optional().describe("The ID of the quiz in the database"),
  answers: z
    .array(z.array(z.int()))
    .default([])
    .describe("The selected option indices per question, from askQuestion"),
  scores: z
    .array(z.number())
    .default([])
    .describe("The scores for each question, from scoreAnswers"),
  finalScore: z
    .number()
    .optional()
    .describe("The final score for the quiz, from scoreAnswers"),
});

export { QuizState };
