import { StateSchema } from "@langchain/langgraph";
import { z } from "zod/v4";
import { QuizSchema } from "./agent.schemas";

const QuizState = new StateSchema({
  readme_url: z.string().describe("The URL of the README file for the quiz"),
  source: z
    .string()
    .default("")
    .describe("The Markdown that fetchSource retrieved from readme_url"),
  quiz: QuizSchema.optional().describe(
    "The quiz generated by generateQuestions from the source Markdown",
  ),
});

export { QuizState };
